apis:
  - name: login
    method: POST
    endpoint: "/login"
    payload: "useEnv"
    headers: "loginHeaders"
    extractCookie: true

  - name: allfeeds
    method: POST
    endpoint: "/rest/web/current/feed/batch/search?module=GEO"
    payload: "useEnv"
    headers: "apiHeaders"
    extractCookie: false

  - name: crimedata
    method: POST
    endpoint: "/rest/web/current/feed/batch/search?module=GEO"
    payload: "useEnv"
    headers: "apiHeaders"
    extractCookie: false

  - name: riskintelligence
    method: POST
    endpoint: "/rest/web/current/feed/batch/search?module=GEO"
    payload: "useEnv"
    headers: "apiHeaders"
    extractCookie: false

  - name: crimeevents
    method: POST
    endpoint: "/rest/web/current/lookup/search?ulookupType=GEO_LEVEL"
    payload: "useEnv"
    headers: "apiHeaders"
    extractCookie: false

  - name: feedpreview
    method: POST
    endpoint: "/rest/web/current/feed/preview?module=GEO"
    payload: "useEnv"
    headers: "apiHeaders"
    extractCookie: false