defaults:
  - type: response_code
    values: [209]

  # - type: response_size_gt
  #   value: 0

  - type: body_not_contains
    values: ["error"]

apis:
  login:
    - type: response_code
      values: [302]

    # - type: response_size_gt
    #   value: 0

    - type: body_not_contains
      values: ["error"]