loginHeaders:
  accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
  accept-language: "en-GB,en;q=0.9"
  cache-control: "no-cache"
  content-type: "application/x-www-form-urlencoded"
  origin: "__BASE_URL__"
  pragma: "no-cache"
  priority: "u=0, i"
  referer: "__BASE_URL__/login.html"
  sec-ch-ua: "\"Google Chrome\";v=\"143\", \"Chromium\";v=\"143\", \"Not A(Brand\";v=\"24\""
  sec-ch-ua-mobile: "?0"
  sec-ch-ua-platform: "\"macOS\""
  sec-fetch-dest: "document"
  sec-fetch-mode: "navigate"
  sec-fetch-site: "same-origin"
  sec-fetch-user: "?1"
  upgrade-insecure-requests: "1"
  user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36"

apiHeaders:
  accept: "application/json, text/plain, */*"
  accept-language: "en-GB,en;q=0.9"
  browser-time-zone: "Asia/Calcutta"
  cache-control: "no-cache"
  content-type: "application/json"
  occd: |
    {"effectiveConnectionSpeed":"4g","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36","platform":"MacIntel"}
  occd-browser-url: "__BASE_URL__/#/geo-threat-management/692eabb1bba3617fadf5143f?refTVT=MONITORING_MAP"
  ocsh: "ee902eea-8d6a-4def-ae06-712cf6ef8742"
  origin: "__BASE_URL__"
  pragma: "no-cache"
  priority: "u=1, i"
  referer: "__BASE_URL__/"
  sec-ch-ua: "\"Google Chrome\";v=\"143\", \"Chromium\";v=\"143\", \"Not A(Brand\";v=\"24\""
  sec-ch-ua-mobile: "?0"
  sec-ch-ua-platform: "\"macOS\""
  sec-fetch-dest: "empty"
  sec-fetch-mode: "cors"
  sec-fetch-site: "same-origin"
  user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36"